package misha.petshelter.ui.theme

const val APP_LOGO_TOP_TIME = 0.068965f
const val APP_LOGO_START_TIME = 0.276595f
const val APP_LOGO_END_TIME = 0.273936f
const val APP_LOGO_BOTTOM_TIME = 0.049261f
const val EDIT_TEXT_HEIGHT = 56
const val EDIT_TEXT_SHAPE = 8
const val EDIT_TEXT_SIZE = 16
const val FIRST_EDIT_TEXT_OFFSET = 15f
const val OFFSET_BETWEEN_EDIT_TEXTS = 2f
const val SELECTOR_VERTICAL_PADDING = 40f
const val SELECTOR_HORIZONTAL_PADDING = 32f
const val SELECTOR_TEXT_SIZE = 16
const val SELECTOR_ACTIVE_SPACER_HEIGHT = 5
const val SELECTOR_INACTIVE_SPACER_HEIGHT = 1